'const' input support for SYCL-DNN
codeplaysoftware/sycl-blas pull request #306
Opened 2021-09-15 14:11 UTC by muhammad-tanvir-1211

2021-09-20 13:13 UTC, KumudhaN approved these changes
Looks good to me.

2021-09-21 11:34 UTC, Bensuo requested changes
LGTM, but please document this new CMake option in `README.md`

2021-09-22 07:21 UTC, ProGTX requested changes

2021-09-22 07:21 UTC, ProGTX commented on cmake/CmakeFunctionHelper.cmake
> +string(FIND ${func} "_const" pos)
```suggestion
string(FIND ${func} "_const" const_pos)
```
Or something like that, to make it more descriptive

2021-09-22 08:42 UTC, mehdi-goli commented on cmake/CmakeFunctionHelper.cmake
> +if(pos)
```suggestion
if(const_pos)
```

2021-09-22 08:43 UTC, mehdi-goli commented on cmake/CmakeFunctionHelper.cmake
> +    if(pos EQUAL -1)
```suggestion
    if(const_pos EQUAL -1)
```

2021-09-23 08:56 UTC, KumudhaN commented
@Bensuo  and @ProGTX. I think all the comments were resolved. Can you approve the PR?

2021-09-23 09:23 UTC, mehdi-goli commented
> @Bensuo and @ProGTX. I think all the comments were resolved. Can you approve the PR?

@KumudhaN please see [this](https://github.com/codeplaysoftware/sycl-blas/pull/306#pullrequestreview-759615731) comment. It is important to have the readme documentation for each option we are putting, so that we know, when, how and why to use it.

2021-09-23 09:37 UTC, KumudhaN commented
> @KumudhaN please see [this](https://github.com/codeplaysoftware/sycl-blas/pull/306#pullrequestreview-759615731) comment. It is important to have the readme documentation for each option we are putting, so that we know, when, how and why to use it.

Thanks, I had missed this. This is fixed now.

2021-09-23 09:58 UTC, Bensuo approved these changes

2021-09-23 12:49 UTC, ProGTX approved these changes

2021-09-23 12:50 UTC, merged